### ISSUE TITLE
during ingest, makes OCR regardless of whether or not islandora_ocr is installed

### ISSUE THREAD

**Issue by wgilling** [discoverygarden/islandora_solution_pack_manuscript#60] opened 2017-08-03 14:32 UTC
The config page /admin/islandora/solution_pack_config/manuscript setting for "OCR datastreams (OCR, HOCR). Requires Islandora OCR module" does not care whether or not the islandora_ocr module is actually installed... if that checkbox is checked, the OCR derivative will be created during ingest.
I would think that the code here should really be checking more than the value of just that "OCR datastreams" checkbox" with "if (module_exists('islandora_ocr')) { ... do the OCR

This is pretty much the same as the islandora_solution_pack_book bug I submitted here: https://jira.duraspace.org/browse/ISLANDORA-2036

**Comment by willtp87** [comment] 2017-10-23 11:12
Thanks for bringing this to our attention, I examined the code in question and believe the issue to be in unsafe usage in the Islandora module(s). I am closing this as a duplicate of the linked Islandora ticket.

**Closed as completed by willtp87** 2017-10-23 11:12 UTC
